// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bneuiubsauqherqrvepu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuZXVpdWJzYXVxaGVycXJ2ZXB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1NDI4MDYsImV4cCI6MjA1MzExODgwNn0.xGy9eqLZtxkEmGKDHZ7M08cilnIlDBH8mzjkj7zkCwk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);